name = "hello-friend-blue"
description = "A simple theme for Hugo. That's it."
features = ["blog", "shortcode", "syntax highlighting"]
homepage = "https://github.com/idokka/hugo-theme-hello-friend-blue"
license = "MIT"
licenselink = "https://github.com/idokka/hugo-theme-hello-friend-blue/blob/master/LICENSE.md"
min_version = 0.147
tags = [
  "blog",
  "clean",
  "customizable",
  "dark",
  "highlighting",
  "light",
  "minimal",
  "monochromatic",
  "multilingual",
  "personal",
  "responsive",
  "simple",
  "technical",
  "social",
  "emoji",
]

[author]
homepage = "https://pimpl.dev/"
name = "idokka"
linkedin = "https://www.linkedin.com/in/omyronenko/"
